// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"database/sql"
	"time"
)

type Person struct {
	ID          int64          `json:"id"`
	Firstname   string         `json:"firstname"`
	Surname     string         `json:"surname"`
	Patronymic  sql.NullString `json:"patronymic"`
	Gender      string         `json:"gender"`
	Age         int64          `json:"age"`
	Nationality string         `json:"nationality"`
	CreatedAt   time.Time      `json:"created_at"`
}
